<?php

$messgae = "welcome to my site.";

// Get a string's length:
echo strlen($message);

// Get number of words in a string:
echo "<br/>";
echo str_word_count($message) . " words.";

//Replace a word in a string:
// original string remains unaffected.
// replaces the word site with the word world.
$msg = "welcome to my site site site.";
// the new parameter $words_replaced is a variable created on the fly that contains the number of words that are replaced.
echo str_replace("site","world",$msg, $words_replaced);
// code for new line, if php code is executed on an online compiler, not on the server where html code is generated by php:
echo "\n";
echo $msg;
echo "\n";
echo $words_replaced;

//Reverse a string, including the words:
echo strrev($message);





?>
